name: Salesforce CI/CD Pipeline

on:
  pull_request:
    branches:
      - QA
    workflow_dispatch:

jobs:
  salesforce-code-analyzer-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        
      - name: 'Run PMD Cloud Scanner'
        uses: pmd/pmd-github-action@v2
        with:
          version: '7.0.0' # Uses a stable, modern PMD engine release
          source: 'force-app' # Points strictly to your Salesforce metadata directory
          rulesets: 'rulesets/apex/quickstart.xml' # Default built-in Salesforce ruleset
          analyzeModifiedFilesOnly: false
